INSERT INTO `Abilities` VALUES (3, 'fliegen');
INSERT INTO `Abilities` VALUES (4, 'tauchen');
INSERT INTO `Accountings` VALUES (1, 3, 1, '2009-11-24');
INSERT INTO `Accountings` VALUES (2, 3, 3, '2009-11-24');
INSERT INTO `Accountings` VALUES (3, 2, 3, '2010-04-23');
INSERT INTO `Offer_Abilities` VALUES (3, 1);
INSERT INTO `Offer_Abilities` VALUES (3, 4);
INSERT INTO `Offer_Abilities` VALUES (4, 2);
INSERT INTO `Offers` VALUES (1, 'flug_ryanair', 120);
INSERT INTO `Offers` VALUES (2, 'tauchgang_malediven', 10);
INSERT INTO `Offers` VALUES (3, 'Surfing', 100);
INSERT INTO `Offers` VALUES (4, 'skydiving', 6);
INSERT INTO `Offers` VALUES (5, 'BASE-jumping', 200);
INSERT INTO `Persons` VALUES (1, 'Huber');
INSERT INTO `Persons` VALUES (2, 'Otto');
INSERT INTO `Persons` VALUES (3, 'Maxmann');
INSERT INTO `Persons_Abilities` VALUES (1, 4);
INSERT INTO `Persons_Abilities` VALUES (2, 3);
